enhancement: decrease service types boxes size
deltaDAO/mvg-catalogue pull request #27
Opened 2022-07-05 17:12 UTC by LucaMilanese90

## Proposed Changes

  - decrease service types boxes size

2022-07-05 18:30 UTC, moritzkirstein requested changes
question(blocking): Could we make use of some already existing CSS variables for these numbers?

suggestion(blocking): If not, I think we should create some to consider reusability with future elements.

2022-07-05 18:41 UTC, LucaMilanese90 commented
I see your point but I'm not sure where we would reuse those variables in the current state, right now this kind of component is not used anywhere else (except for the popular tags, which we just removed)

2022-07-06 10:43 UTC, moritzkirstein commented
Agreed. Would be an adjustment that hopefully saves us the hassle of refactoring in the future. (e.g. reintroducing the categories -> can make use of this var)

2022-07-08 09:40 UTC, moritzkirstein approved these changes

2022-07-11 10:02 UTC, merged